"""OpenAI Chat Completions API endpoints."""

import time
import uuid
from collections.abc import AsyncGenerator
from dataclasses import dataclass
from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import JSONResponse, StreamingResponse
from openai.types import CompletionUsage
from openai.types.chat import ChatCompletion, ChatCompletionChunk, ChatCompletionMessage
from openai.types.chat.chat_completion import Choice
from openai.types.chat.chat_completion_chunk import Choice as ChunkChoice
from openai.types.chat.chat_completion_chunk import (
    ChoiceDelta,
    ChoiceDeltaToolCall,
    ChoiceDeltaToolCallFunction,
)

from llmock.config import Config, get_config
from llmock.schemas.chat import ChatCompletionRequest
from llmock.strategies import StrategyResponse, StrategyResponseType
from llmock.strategies.strategy_composition import ChatCompositionStrategy

router = APIRouter(prefix="/v1", tags=["chat"])


@router.post("/chat/completions", response_model=None)
async def create_chat_completion(
    request: ChatCompletionRequest,
    config: Annotated[Config, Depends(get_config)],
) -> ChatCompletion | StreamingResponse | JSONResponse:
    """Create a chat completion.

    Creates a model response for the given chat conversation.
    Supports both streaming and non-streaming responses.

    The actual response content is generated by the strategy.
    The endpoint handles streaming vs non-streaming output formatting.
    """
    # Validate model exists
    validate_model(request.model, config)

    # Generate response via the composition strategy chain
    responses = ChatCompositionStrategy(config).generate_response(request)

    # Check for errors before creating the response (streaming or not)
    error = next((r for r in responses if r.type == StrategyResponseType.ERROR), None)
    if error:
        return build_error_json_response(error)

    if request.stream:
        return StreamingResponse(
            generate_streaming_response(request, responses),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            },
        )
    else:
        return create_non_streaming_response(request, responses)


def create_non_streaming_response(
    request: ChatCompletionRequest,
    responses: list[StrategyResponse],
) -> ChatCompletion | JSONResponse:
    """Create a non-streaming chat completion response.

    Each StrategyResponse becomes a separate Choice (order preserved).
    The finish reason is determined by the last response's type:
    ``tool_calls`` if the last item is a TOOL_CALL, ``stop`` otherwise.
    """

    completion_id = generate_completion_id()
    created = int(time.time())

    prompt_text = " ".join(msg.content or "" for msg in request.messages if msg.content)
    prompt_tokens = estimate_tokens(prompt_text)
    completion_tokens = estimate_tokens(
        " ".join(r.content for r in responses if r.content)
    )

    choices = [to_chat_choice(i, r) for i, r in enumerate(responses)]

    return ChatCompletion(
        id=completion_id,
        created=created,
        model=request.model,
        object="chat.completion",
        choices=choices,
        usage=CompletionUsage(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
        ),
    )


def to_chat_choice(index: int, resp: StrategyResponse) -> Choice:
    """Convert a StrategyResponse into a ChatCompletion Choice.

    The ``finish_reason`` is derived from the response type.
    """
    from openai.types.chat.chat_completion_message_tool_call import (
        ChatCompletionMessageToolCall,
        Function,
    )

    if resp.type == StrategyResponseType.TOOL_CALL:
        message = ChatCompletionMessage(
            role="assistant",
            content=None,
            tool_calls=[
                ChatCompletionMessageToolCall(
                    id=f"call_{uuid.uuid4().hex}",
                    type="function",
                    function=Function(
                        name=resp.name,
                        arguments=resp.content,
                    ),
                )
            ],
        )
        finish_reason = "tool_calls"
    else:
        message = ChatCompletionMessage(
            role="assistant",
            content=resp.content,
        )
        finish_reason = "stop"

    return Choice(
        index=index,
        message=message,
        finish_reason=finish_reason,
    )


@dataclass
class _StreamContext:
    """Mutable state shared across streaming chunk helpers."""

    completion_id: str
    created: int
    model: str
    is_first_chunk: bool = True
    has_tool_calls: bool = False
    tool_call_index: int = 0


async def generate_streaming_response(
    request: ChatCompletionRequest,
    responses: list[StrategyResponse],
) -> AsyncGenerator[str, None]:
    """Generate SSE streaming chunks for chat completion.

    Iterates through all responses in order, yielding chunks for each:
    - TEXT responses are streamed word by word.
    - TOOL_CALL responses are each emitted as a single chunk.
    - ERROR responses raise an HTTPException, aborting the stream.
    """
    ctx = _StreamContext(
        completion_id=generate_completion_id(),
        created=int(time.time()),
        model=request.model,
    )

    for resp in responses:
        for chunk in _create_streaming_chunks(ctx, resp):
            yield f"data: {chunk.model_dump_json()}\n\n"

    yield f"data: {_create_finish_reason_chunk(ctx).model_dump_json()}\n\n"

    if _include_usage(request):
        yield f"data: {_create_usage_chunk(ctx, request, responses).model_dump_json()}\n\n"

    yield "data: [DONE]\n\n"


def _create_streaming_chunks(
    ctx: _StreamContext,
    resp: StrategyResponse,
) -> list[ChatCompletionChunk]:
    """Create chunk objects for a single StrategyResponse.

    Returns a list of ``ChatCompletionChunk`` objects.
    """
    if resp.type == StrategyResponseType.TOOL_CALL:
        return _create_tool_call_chunk(ctx, resp)

    return _create_text_chunks(ctx, resp)


def _create_tool_call_chunk(
    ctx: _StreamContext,
    resp: StrategyResponse,
) -> list[ChatCompletionChunk]:
    """Create a single chunk for a tool call response."""
    ctx.has_tool_calls = True
    tool_call_id = f"call_{uuid.uuid4().hex}"

    delta_kwargs: dict[str, Any] = {
        "content": None,
        "tool_calls": [
            ChoiceDeltaToolCall(
                index=ctx.tool_call_index,
                id=tool_call_id,
                type="function",
                function=ChoiceDeltaToolCallFunction(
                    name=resp.name,
                    arguments=resp.content,
                ),
            )
        ],
    }
    if ctx.is_first_chunk:
        delta_kwargs["role"] = "assistant"
        ctx.is_first_chunk = False

    chunk = ChatCompletionChunk(
        id=ctx.completion_id,
        created=ctx.created,
        model=ctx.model,
        object="chat.completion.chunk",
        choices=[
            ChunkChoice(
                index=0,
                delta=ChoiceDelta(**delta_kwargs),
                finish_reason=None,
            )
        ],
    )
    ctx.tool_call_index += 1
    return [chunk]


def _create_text_chunks(
    ctx: _StreamContext,
    resp: StrategyResponse,
) -> list[ChatCompletionChunk]:
    """Create chunks for a text response (role + word-by-word content)."""
    chunks: list[ChatCompletionChunk] = []

    if ctx.is_first_chunk:
        role_chunk = ChatCompletionChunk(
            id=ctx.completion_id,
            created=ctx.created,
            model=ctx.model,
            object="chat.completion.chunk",
            choices=[
                ChunkChoice(
                    index=0,
                    delta=ChoiceDelta(role="assistant", content=""),
                    finish_reason=None,
                )
            ],
        )
        chunks.append(role_chunk)
        ctx.is_first_chunk = False

    words = resp.content.split(" ")
    for i, word in enumerate(words):
        text = word if i == 0 else f" {word}"
        chunk = ChatCompletionChunk(
            id=ctx.completion_id,
            created=ctx.created,
            model=ctx.model,
            object="chat.completion.chunk",
            choices=[
                ChunkChoice(
                    index=0,
                    delta=ChoiceDelta(content=text),
                    finish_reason=None,
                )
            ],
        )
        chunks.append(chunk)

    return chunks


def _create_finish_reason_chunk(ctx: _StreamContext) -> ChatCompletionChunk:
    """Create the final chunk carrying the finish_reason."""
    finish_reason = "tool_calls" if ctx.has_tool_calls else "stop"
    return ChatCompletionChunk(
        id=ctx.completion_id,
        created=ctx.created,
        model=ctx.model,
        object="chat.completion.chunk",
        choices=[
            ChunkChoice(
                index=0,
                delta=ChoiceDelta(),
                finish_reason=finish_reason,
            )
        ],
    )


def _create_usage_chunk(
    ctx: _StreamContext,
    request: ChatCompletionRequest,
    responses: list[StrategyResponse],
) -> ChatCompletionChunk:
    """Create a usage chunk with token counts."""
    prompt_text = " ".join(msg.content or "" for msg in request.messages if msg.content)
    prompt_tokens = estimate_tokens(prompt_text)
    completion_tokens = estimate_tokens(" ".join(r.content for r in responses))

    return ChatCompletionChunk(
        id=ctx.completion_id,
        created=ctx.created,
        model=ctx.model,
        object="chat.completion.chunk",
        choices=[],
        usage=CompletionUsage(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
        ),
    )


def validate_model(model_id: str, config: Config) -> None:
    """Validate that the model exists in config."""
    models_config = config.get("models", [])
    model_ids = [m["id"] for m in models_config]

    if model_ids and model_id not in model_ids:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": {
                    "message": f"The model '{model_id}' does not exist",
                    "type": "invalid_request_error",
                    "param": "model",
                    "code": "model_not_found",
                }
            },
        )


def build_error_json_response(error: StrategyResponse) -> JSONResponse:
    """Build a JSONResponse from an ERROR StrategyResponse."""
    return JSONResponse(
        status_code=error.status_code or 500,
        content={
            "error": {
                "message": error.content,
                "type": error.error_type or "api_error",
                "param": None,
                "code": error.error_code or "error",
            }
        },
    )


def generate_completion_id() -> str:
    """Generate a unique completion ID."""
    return f"chatcmpl-{uuid.uuid4().hex[:24]}"


def estimate_tokens(text: str) -> int:
    """Estimate token count (rough approximation: ~4 chars per token)."""
    return max(1, len(text) // 4)


def _include_usage(request: ChatCompletionRequest) -> bool:
    """Check if usage should be included in streaming chunks."""
    return request.stream_options is not None and request.stream_options.include_usage
