"""OpenAI Responses API endpoints."""

import asyncio
import json
import time
import uuid
from collections.abc import AsyncGenerator
from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import JSONResponse, StreamingResponse

from llmock.config import Config, get_config
from llmock.routers.chat import build_error_json_response
from openai.types.responses import (
    Response,
    ResponseFunctionToolCall,
    ResponseOutputMessage,
    ResponseOutputText,
    ResponseUsage,
)
from openai.types.responses.response_usage import (
    InputTokensDetails,
    OutputTokensDetails,
)

from llmock.schemas.responses import (
    InputMessage,
    InputTextContent,
    ResponseCreateRequest,
    SimpleInputMessage,
)
from llmock.strategies import (
    StrategyResponseType,
)
from llmock.strategies.strategy_composition import ResponseCompositionStrategy

router = APIRouter(prefix="/v1", tags=["responses"])


@router.post("/responses", response_model=None)
async def create_response_endpoint(
    request: ResponseCreateRequest,
    config: Annotated[Config, Depends(get_config)],
) -> Response | StreamingResponse | JSONResponse:
    """Create a model response.

    Creates a model response for the given input.
    Supports both streaming and non-streaming responses.

    The actual response content is generated by the strategy.
    The endpoint handles streaming vs non-streaming output formatting.
    """
    # Validate model exists
    validate_model(request.model, config)

    # Generate response via the composition strategy chain
    responses = ResponseCompositionStrategy(config).generate_response(request)

    # Check if the strategy returned an error
    if responses and responses[0].type == StrategyResponseType.ERROR:
        return build_error_json_response(responses[0])

    # Route based on response types
    has_tool_calls = any(r.type == StrategyResponseType.TOOL_CALL for r in responses)

    if has_tool_calls:
        tool_call_items = [
            r for r in responses if r.type == StrategyResponseType.TOOL_CALL
        ]
        tool_call_info = {
            "tool_call_id": f"call_{uuid.uuid4().hex}",
            "function_name": tool_call_items[0].name,
            "arguments": tool_call_items[0].content,
        }

        if request.stream:
            return StreamingResponse(
                generate_streaming_tool_call_response(request, tool_call_info),
                media_type="text/event-stream",
                headers={
                    "Cache-Control": "no-cache",
                    "Connection": "keep-alive",
                },
            )

        return create_tool_call_response(request, tool_call_info)

    # Text response - combine all text items
    text_items = [r for r in responses if r.type == StrategyResponseType.TEXT]
    response_content = text_items[0].content if text_items else ""

    if request.stream:
        return StreamingResponse(
            generate_streaming_response(request, response_content),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            },
        )

    return create_response(request, response_content)


def create_response(
    request: ResponseCreateRequest,
    response_content: str,
) -> Response:
    """Create a response object."""
    response_id = generate_response_id()
    message_id = generate_message_id()
    created_at = int(time.time())

    # Calculate token usage
    input_text = extract_input_text(request)
    if request.instructions:
        input_text = f"{request.instructions} {input_text}"
    input_tokens = estimate_tokens(input_text)
    output_tokens = estimate_tokens(response_content)

    return Response(
        id=response_id,
        object="response",
        created_at=created_at,
        status="completed",
        completed_at=created_at,
        instructions=request.instructions,
        max_output_tokens=request.max_output_tokens,
        model=request.model,
        output=[
            ResponseOutputMessage(
                type="message",
                id=message_id,
                status="completed",
                role="assistant",
                content=[
                    ResponseOutputText(
                        type="output_text",
                        text=response_content,
                        annotations=[],
                    )
                ],
            )
        ],
        parallel_tool_calls=request.parallel_tool_calls,
        previous_response_id=request.previous_response_id,
        temperature=request.temperature,
        tool_choice="auto",
        tools=[],
        top_p=request.top_p,
        truncation=request.truncation,
        usage=ResponseUsage(
            input_tokens=input_tokens,
            input_tokens_details=InputTokensDetails(cached_tokens=0),
            output_tokens=output_tokens,
            output_tokens_details=OutputTokensDetails(reasoning_tokens=0),
            total_tokens=input_tokens + output_tokens,
        ),
        metadata=request.metadata or {},
    )


async def generate_streaming_response(
    request: ResponseCreateRequest,
    response_content: str,
) -> AsyncGenerator[str, None]:
    """Generate SSE streaming events for response creation."""
    response_id = generate_response_id()
    message_id = generate_message_id()
    created_at = int(time.time())

    # Calculate token usage
    input_text = extract_input_text(request)
    if request.instructions:
        input_text = f"{request.instructions} {input_text}"
    input_tokens = estimate_tokens(input_text)
    output_tokens = estimate_tokens(response_content)

    # Event: response.created
    created_event = {
        "type": "response.created",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "in_progress",
            "model": request.model,
            "output": [],
        },
    }
    yield f"event: response.created\ndata: {_json_dumps(created_event)}\n\n"

    # Event: response.in_progress
    in_progress_event = {
        "type": "response.in_progress",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "in_progress",
            "model": request.model,
            "output": [],
        },
    }
    yield f"event: response.in_progress\ndata: {_json_dumps(in_progress_event)}\n\n"

    # Event: response.output_item.added
    item_added_event = {
        "type": "response.output_item.added",
        "output_index": 0,
        "item": {
            "type": "message",
            "id": message_id,
            "status": "in_progress",
            "role": "assistant",
            "content": [],
        },
    }
    yield f"event: response.output_item.added\ndata: {_json_dumps(item_added_event)}\n\n"

    # Event: response.content_part.added
    content_part_added_event = {
        "type": "response.content_part.added",
        "item_id": message_id,
        "output_index": 0,
        "content_index": 0,
        "part": {"type": "output_text", "text": "", "annotations": []},
    }
    yield f"event: response.content_part.added\ndata: {_json_dumps(content_part_added_event)}\n\n"

    # Stream content word by word
    words = response_content.split(" ")
    for i, word in enumerate(words):
        # Add space before word (except first)
        delta = word if i == 0 else f" {word}"

        delta_event = {
            "type": "response.output_text.delta",
            "item_id": message_id,
            "output_index": 0,
            "content_index": 0,
            "delta": delta,
        }
        yield f"event: response.output_text.delta\ndata: {_json_dumps(delta_event)}\n\n"

        # Small delay to simulate streaming
        await asyncio.sleep(0.01)

    # Event: response.output_text.done
    text_done_event = {
        "type": "response.output_text.done",
        "item_id": message_id,
        "output_index": 0,
        "content_index": 0,
        "text": response_content,
    }
    yield f"event: response.output_text.done\ndata: {_json_dumps(text_done_event)}\n\n"

    # Event: response.content_part.done
    content_part_done_event = {
        "type": "response.content_part.done",
        "item_id": message_id,
        "output_index": 0,
        "content_index": 0,
        "part": {"type": "output_text", "text": response_content, "annotations": []},
    }
    yield f"event: response.content_part.done\ndata: {_json_dumps(content_part_done_event)}\n\n"

    # Event: response.output_item.done
    item_done_event = {
        "type": "response.output_item.done",
        "output_index": 0,
        "item": {
            "type": "message",
            "id": message_id,
            "status": "completed",
            "role": "assistant",
            "content": [
                {"type": "output_text", "text": response_content, "annotations": []}
            ],
        },
    }
    yield f"event: response.output_item.done\ndata: {_json_dumps(item_done_event)}\n\n"

    # Event: response.completed
    completed_event = {
        "type": "response.completed",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "completed",
            "completed_at": int(time.time()),
            "model": request.model,
            "output": [
                {
                    "type": "message",
                    "id": message_id,
                    "status": "completed",
                    "role": "assistant",
                    "content": [
                        {
                            "type": "output_text",
                            "text": response_content,
                            "annotations": [],
                        }
                    ],
                }
            ],
            "usage": {
                "input_tokens": input_tokens,
                "input_tokens_details": {"cached_tokens": 0},
                "output_tokens": output_tokens,
                "output_tokens_details": {"reasoning_tokens": 0},
                "total_tokens": input_tokens + output_tokens,
            },
        },
    }
    yield f"event: response.completed\ndata: {_json_dumps(completed_event)}\n\n"


def _json_dumps(obj: dict[str, Any]) -> str:
    """Convert dict to JSON string."""
    return json.dumps(obj)


def generate_tool_call_item_id() -> str:
    """Generate a unique function call item ID."""
    return f"fc_{uuid.uuid4().hex}"


def create_tool_call_response(
    request: ResponseCreateRequest,
    tool_call_info: dict,
) -> Response:
    """Create a non-streaming response with a tool call output item."""
    response_id = generate_response_id()
    item_id = generate_tool_call_item_id()
    created_at = int(time.time())

    input_text = extract_input_text(request)
    if request.instructions:
        input_text = f"{request.instructions} {input_text}"
    input_tokens = estimate_tokens(input_text)
    output_tokens = estimate_tokens(
        json.dumps(
            {
                "name": tool_call_info["function_name"],
                "arguments": tool_call_info["arguments"],
            }
        )
    )

    return Response(
        id=response_id,
        object="response",
        created_at=created_at,
        status="completed",
        completed_at=created_at,
        instructions=request.instructions,
        max_output_tokens=request.max_output_tokens,
        model=request.model,
        output=[
            ResponseFunctionToolCall(
                type="function_call",
                id=item_id,
                call_id=tool_call_info["tool_call_id"],
                name=tool_call_info["function_name"],
                arguments=tool_call_info["arguments"],
                status="completed",
            )
        ],
        parallel_tool_calls=request.parallel_tool_calls,
        previous_response_id=request.previous_response_id,
        temperature=request.temperature,
        tool_choice="auto",
        tools=request.tools or [],
        top_p=request.top_p,
        truncation=request.truncation,
        usage=ResponseUsage(
            input_tokens=input_tokens,
            input_tokens_details=InputTokensDetails(cached_tokens=0),
            output_tokens=output_tokens,
            output_tokens_details=OutputTokensDetails(reasoning_tokens=0),
            total_tokens=input_tokens + output_tokens,
        ),
        metadata=request.metadata or {},
    )


async def generate_streaming_tool_call_response(
    request: ResponseCreateRequest,
    tool_call_info: dict,
) -> AsyncGenerator[str, None]:
    """Generate SSE streaming events for a tool call response."""
    response_id = generate_response_id()
    item_id = generate_tool_call_item_id()
    created_at = int(time.time())

    tool_call_id = tool_call_info["tool_call_id"]
    function_name = tool_call_info["function_name"]
    arguments = tool_call_info["arguments"]

    input_text = extract_input_text(request)
    if request.instructions:
        input_text = f"{request.instructions} {input_text}"
    input_tokens = estimate_tokens(input_text)
    output_tokens = estimate_tokens(
        json.dumps({"name": function_name, "arguments": arguments})
    )

    # Event: response.created
    created_event = {
        "type": "response.created",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "in_progress",
            "model": request.model,
            "output": [],
        },
    }
    yield f"event: response.created\ndata: {_json_dumps(created_event)}\n\n"

    # Event: response.in_progress
    in_progress_event = {
        "type": "response.in_progress",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "in_progress",
            "model": request.model,
            "output": [],
        },
    }
    yield f"event: response.in_progress\ndata: {_json_dumps(in_progress_event)}\n\n"

    # Event: response.output_item.added (function_call item)
    item_added_event = {
        "type": "response.output_item.added",
        "output_index": 0,
        "item": {
            "type": "function_call",
            "id": item_id,
            "call_id": tool_call_id,
            "name": function_name,
            "arguments": "",
            "status": "in_progress",
        },
    }
    yield f"event: response.output_item.added\ndata: {_json_dumps(item_added_event)}\n\n"

    # Event: response.function_call_arguments.delta
    delta_event = {
        "type": "response.function_call_arguments.delta",
        "item_id": item_id,
        "output_index": 0,
        "delta": arguments,
    }
    yield f"event: response.function_call_arguments.delta\ndata: {_json_dumps(delta_event)}\n\n"

    await asyncio.sleep(0.01)

    # Event: response.function_call_arguments.done
    done_event = {
        "type": "response.function_call_arguments.done",
        "item_id": item_id,
        "output_index": 0,
        "arguments": arguments,
    }
    yield f"event: response.function_call_arguments.done\ndata: {_json_dumps(done_event)}\n\n"

    # Event: response.output_item.done
    item_done_event = {
        "type": "response.output_item.done",
        "output_index": 0,
        "item": {
            "type": "function_call",
            "id": item_id,
            "call_id": tool_call_id,
            "name": function_name,
            "arguments": arguments,
            "status": "completed",
        },
    }
    yield f"event: response.output_item.done\ndata: {_json_dumps(item_done_event)}\n\n"

    # Event: response.completed
    completed_event = {
        "type": "response.completed",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "completed",
            "completed_at": int(time.time()),
            "model": request.model,
            "output": [
                {
                    "type": "function_call",
                    "id": item_id,
                    "call_id": tool_call_id,
                    "name": function_name,
                    "arguments": arguments,
                    "status": "completed",
                }
            ],
            "usage": {
                "input_tokens": input_tokens,
                "input_tokens_details": {"cached_tokens": 0},
                "output_tokens": output_tokens,
                "output_tokens_details": {"reasoning_tokens": 0},
                "total_tokens": input_tokens + output_tokens,
            },
        },
    }
    yield f"event: response.completed\ndata: {_json_dumps(completed_event)}\n\n"


def validate_model(model_id: str, config: Config) -> None:
    """Validate that the model exists in config."""
    models_config = get_models_config(config)
    model_ids = [m["id"] for m in models_config]

    if model_ids and model_id not in model_ids:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": {
                    "message": f"The model '{model_id}' does not exist",
                    "type": "invalid_request_error",
                    "param": "model",
                    "code": "model_not_found",
                }
            },
        )


def get_models_config(config: Config) -> list[dict[str, Any]]:
    """Extract models list from config."""
    return config.get("models", [])


def generate_response_id() -> str:
    """Generate a unique response ID."""
    return f"resp_{uuid.uuid4().hex}"


def generate_message_id() -> str:
    """Generate a unique message ID."""
    return f"msg_{uuid.uuid4().hex}"


def estimate_tokens(text: str) -> int:
    """Estimate token count (rough approximation: ~4 chars per token)."""
    return max(1, len(text) // 4)


def extract_input_text(request: ResponseCreateRequest) -> str:
    """Extract text from input for token counting."""
    if isinstance(request.input, str):
        return request.input

    texts: list[str] = []
    for item in request.input:
        if isinstance(item, SimpleInputMessage):
            texts.append(item.content)
        elif isinstance(item, InputMessage):
            if isinstance(item.content, str):
                texts.append(item.content)
            else:
                for content_item in item.content:
                    if isinstance(content_item, InputTextContent):
                        texts.append(content_item.text)
    return " ".join(texts)
